// Generated by dts-bundle v0.7.3

declare module '@template/uteis' {
    export * from '@template/uteis/store/Task.store';
}

declare module '@template/uteis/store/Task.store' {
    export interface ITask {
        key: string;
        description: string;
        status: "new" | "in progress" | "done";
    }
    export interface ITaskStore {
        tasks: Map<string, ITask>;
        addTask: (task: ITask) => void;
        getTask: (key: string) => ITask;
        removeTask: (key: string) => void;
        clear: VoidFunction;
    }
    export const useTaskStore: import("zustand").StoreApi<ITaskStore>;
    export {};
}

