// Generated by dts-bundle v0.7.3
// Dependencies for this module:
//   ../reactstrap

declare module '@lms/layout' {
    export * from 'reactstrap';
    export const bootstrap: import("single-spa").LifeCycleFn<any>, mount: import("single-spa").LifeCycleFn<any>, unmount: import("single-spa").LifeCycleFn<any>;
}

